services:
  carrinho:
    build:
      context: .
      dockerfile: ./Carrinho/Dockerfile
    container_name: carrinho-api
    ports:
      - "8080:8080"
    networks:
      - magalu-network
    depends_on:
      - rabbitmq
  estoque:
    build:
      context: .
      dockerfile: ./Estoque/Dockerfile
    container_name: estoque-api
    ports:
      - "8081:8081"
    networks:
      - magalu-network
    depends_on:
      - rabbitmq
      - sqlserver
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magalu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 10s
      retries: 5
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - magalu-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://redis:6379"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - magalu-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - magalu-network
    container_name: sqlserver
    volumes:
      - sqlserver_volume_data:/var/opt/mssql

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  sqlserver_volume_data:

networks:
  magalu-network:
    driver: bridge