services:
  carrinho:
    build:
      context: .
      dockerfile: ./Carrinho/Dockerfile
    container_name: carrinho-api
    ports:
      - "8080:8080"
    networks:
      - magalu-network
    environment:
      WAIT_HOSTS: rabbitmq:5672, redis:6379
      WAIT_BEFORE: 10
  estoque:
    build:
      context: .
      dockerfile: ./Estoque/Dockerfile
    container_name: estoque-api
    ports:
      - "8081:8081"
    networks:
      - magalu-network
    environment:
      WAIT_HOSTS: rabbitmq:5672, redis:6379
      WAIT_BEFORE: 10
  rabbitmq:
    image: bitnami/rabbitmq:3.10.8-debian-11-r4
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magalu-network
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - magalu-network
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - magalu-network
volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  magalu-network:
    driver: bridge