// <auto-generated />
using System;
using Magalu.Estoque.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magalu.Estoque.Persistence.Migrations
{
    [DbContext(typeof(EstoqueContext))]
    partial class EstoqueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magalu.Estoque.Domain.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96661d5f-63f3-458e-a1e5-c69afb03970c"),
                            Nome = "Item 1"
                        },
                        new
                        {
                            Id = new Guid("7dd5e92b-40d4-4e8b-a678-137a7ca7e4ed"),
                            Nome = "Item 2"
                        },
                        new
                        {
                            Id = new Guid("3d7aa781-8a49-4409-a15a-4b9e352c06ef"),
                            Nome = "Item 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
